#!/usr/bin/env python3
"""
PreToolUse hook — block Claude from reading .env files.

Triggered by: Read, Glob, Grep, LS, Bash tool calls.
Purpose: Prevent Claude from ingesting real secrets during agentic sessions.
         Claude should read .env.template (committed, no real values) not .env.

Why this matters:
    During long agentic sessions Claude reads many files to build context.
    If it reads .env it may inadvertently include secrets in its context window,
    in summaries, in logs, or in generated code. Blocking the read eliminates
    the risk entirely — Claude doesn't need the real values to do its job.

What Claude should use instead:
    - .env.template  — understand what variables exist and their purpose
    - os.environ / pydantic BaseSettings — reference env vars by name in code
    - Never hardcode values, never read .env directly

Source: Anthropic free course best practices for agentic security.

exit 1 → block the tool call and explain why.
exit 0 → allow the tool call to proceed.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

# Files Claude must never read.
# .env.template is explicitly allowed — it has no real values.
BLOCKED_FILENAMES = {
    ".env",
    ".env.local",
    ".env.production",
    ".env.staging",
    ".env.development",
    ".env.test",
    ".env.secrets",
    ".env.claude",   # generated by configure.py, may contain API URL overrides
}

# Patterns in Bash commands that would read .env content into Claude's context.
# We want to catch: cat .env, source .env, . .env, grep .env, etc.
BASH_ENV_READ_PATTERNS = [
    r"\bcat\s+['\"]?\.env['\"]?(?:\s|$)",
    r"\bsource\s+['\"]?\.env['\"]?(?:\s|$)",
    r"^\.\s+['\"]?\.env['\"]?(?:\s|$)",          # POSIX `. .env`
    r"\bgrep\s+.*['\"]?\.env['\"]?(?:\s|$)",
    r"\bless\s+['\"]?\.env['\"]?(?:\s|$)",
    r"\bmore\s+['\"]?\.env['\"]?(?:\s|$)",
    r"\bhead\s+.*['\"]?\.env['\"]?(?:\s|$)",
    r"\btail\s+.*['\"]?\.env['\"]?(?:\s|$)",
]


def is_blocked_path(path_str: str) -> bool:
    """Return True if the path resolves to a blocked .env file."""
    p = Path(path_str)
    # Match on filename only — .env in any subdirectory is blocked
    return p.name in BLOCKED_FILENAMES


def is_blocked_bash(command: str) -> bool:
    """Return True if the bash command would read a .env file."""
    for pattern in BASH_ENV_READ_PATTERNS:
        if re.search(pattern, command, re.IGNORECASE | re.MULTILINE):
            return True
    return False


def block(reason: str) -> None:
    """Print block reason and exit 1."""
    print(f"BLOCKED: {reason}", file=sys.stderr)
    print("", file=sys.stderr)
    print("Claude should not read .env files — they may contain real secrets.", file=sys.stderr)
    print("Use .env.template to understand available variables (no real values).", file=sys.stderr)
    print("Reference env vars by name in code: os.environ['VAR'] or pydantic BaseSettings.", file=sys.stderr)
    sys.exit(1)


def main() -> None:
    """Check tool call for .env access attempts."""
    payload = json.loads(sys.stdin.read())
    tool_name = payload.get("tool_name", "")
    tool_input = payload.get("tool_input", {})

    # --- File read tools ---
    if tool_name == "Read":
        path = tool_input.get("file_path", "") or tool_input.get("path", "")
        if path and is_blocked_path(path):
            block(f"Attempted to read '{Path(path).name}'")

    # --- Glob / LS — block if pattern would match .env files ---
    elif tool_name in ("Glob", "LS"):
        pattern = tool_input.get("pattern", "") or tool_input.get("path", "")
        # Be conservative: if the glob pattern could match a .env file, block it.
        # e.g. ".env*", ".*", "**/.env" all warrant blocking.
        if pattern and re.search(r"(^|/)\.env", pattern):
            block(f"Glob/LS pattern '{pattern}' could match .env files")

    # --- Grep — block if searching in .env files ---
    elif tool_name == "Grep":
        include = tool_input.get("include", "")
        path = tool_input.get("path", "")
        if include and is_blocked_path(include):
            block(f"Grep include pattern targets '{include}'")
        if path and is_blocked_path(path):
            block(f"Grep path targets '{Path(path).name}'")

    # --- Bash — block commands that read .env content ---
    elif tool_name == "Bash":
        command = tool_input.get("command", "")
        if command and is_blocked_bash(command):
            block("Bash command would read .env file content")


if __name__ == "__main__":
    main()
